config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: { maximum:30 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー『#{@user.name}』を登録しました"
    else
      render :new
    end
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー『#{@user.name}』を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー『#{@user.name}』を削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end




  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      redirect_to "/tasks/#{@task.id}", notice: "タスク『#{@task.name}』を登録しました"
    else
      render :new
    end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    @task.update!(task_params)
    redirect_to "/tasks/#{@task.id}", notice: "タスク『#{@task.name}』を更新しました"
  end

  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: "タスク『#{@task.name}』を削除しました"
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end

  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.erb
<% if user.errors.present? %>
  <ul class="ul#error_explanation">
    <% user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [:admin, user], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <br>
  <div class="form-check">
    <%= f.label :admin, '管理者権限', class: 'form-check-label' %>
    <%= f.check_box :admin, class: 'form-check-input' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <br>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集</h1>

<%= link_to '一覧', admin_users_path, class: 'nav-link' %>

<%= render partial: 'form', locals: {user: @user } %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>

<%= link_to '新規登録', new_admin_user_path ,class: 'btn btn-primary' %>

<table class="table">
    <thead>
        <tr>
            <th><%= User.human_attribute_name :name %></th>
            <th><%= User.human_attribute_name(:email) %></th>
            <th><%= User.human_attribute_name(:admin) %></th>
            <th><%= User.human_attribute_name(:created_at) %></th>
            <th><%= User.human_attribute_name(:updated_at) %></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <th><%= link_to user.name, [:admin, user] %></th>
                <th><%= user.email %></th>
                <th><%= user.admin? ? 'あり' : 'なし' %></th>
                <th><%= user.created_at %></th>
                <th><%= user.updated_at %></th>
                <th>
                  <%= link_to '編集', edit_admin_user_path(user) ,class: 'btn btn-primary' %>
                  <%= link_to '削除', [:admin, user], method: :delete, data: { confirm: "タスク『#{user.name}』を削除します。よろしいですか？"}, class: 'btn btn-primary' %>
                </th>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/users/new.html.erb
<h1>ユーザー登録</h1>

<%= link_to '一覧', admin_users_path, class: 'nav-link' %>

<%= render partial: 'form', locals: {user: @user } %>

app/views/admin/users/show.html.erb
<h1>ユーザーの詳細</h1>
<%= link_to '一覧', admin_users_path, class: 'btn btn-primary' %>
<%= link_to '編集', edit_admin_user_path ,class: 'btn btn-primary' %>
<%= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "タスク『#{@user.name}』を削除します。よろしいですか？"}, class: 'btn btn-primary' %>

<table class="table">
  <tbody>
    <tr>
      <th><%= User.human_attribute_name :id %></th>
      <td><%= @user.id %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name :name %></th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name :email %></th>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name :admin %></th>
      <td><%= @user.admin? ? 'あり' : 'なし' %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name :created_at %></th>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <th><%= User.human_attribute_name :updated_at %></th>
      <td><%= @user.updated_at %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Taskleaf</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if current_user %>
              <li class="nav-item">
                <%= link_to 'タスク一覧', tasks_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'ログイン', login_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">

      <% if flash[:notice] %>
        <div class="alert alert-primary" role="alert">
          <p><%= notice %></p>
        </div>
      <% end %>
      
      <% if flash[:alert] %>
        <div class="alert alert-primary" role="alert">
          <p><%= alert %></p>
        </div>
      <% end %>

      <%= yield %>
    </div>

    
  </body>
</html>

app/views/tasks/_form.html.erb
<% if task.errors.present? %>
  <ul class="ul#error_explanation">
    <% task.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: task, local: true do |form| %>
  <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control', id: 'task_name' %>
  </div>
  <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, rows: 5, class: 'form-control', id: 'task_description' %>
  </div>
  <br>
  <%= form.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>
<%= link_to '投稿一覧へ', tasks_path, class: 'nav-link' %>

<%= render partial: 'form',locals: {task: @task } %>

app/views/tasks/index.html.erb
<div class="container">
    <h2>タスク一覧</h2>
    <%= link_to '新規作成', new_task_path ,class: 'btn btn-primary' %>

    <table class="table">
        <thead>
            <tr>
                <th><%= Task.human_attribute_name :name %></th>
                <th><%= Task.human_attribute_name(:created_at) %></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <% @tasks.each do |task| %>
                <tr>
                    <th><%= link_to task.name, task %></th>
                    <th><%= task.created_at %></th>
                    <th><%= link_to '編集', edit_task_path(task) ,class: 'btn btn-primary' %></th>
                    <th><%= link_to '削除', task, method: :delete, data: { confirm: "タスク『#{task.name}』を削除します。よろしいですか？"}, class: 'btn btn-primary' %></th>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/tasks/new.html.erb
<div class="container-fluid">
    <h1>タスクの新規投稿</h1>
    <div class= "nav.justify-content-end">
        <%= link_to '投稿一覧へ', tasks_path, class: 'nav-link' %>
    </div>

    <%= render partial: 'form',locals: {task: @task } %>
    
</div>

app/views/tasks/show.html.erb
<h1>タスクの詳細</h1>
<%= link_to '投稿一覧', tasks_path, class: 'btn btn-primary' %>
<%= link_to '編集', edit_task_path ,class: 'btn btn-primary' %>
<%= link_to '削除', @task, method: :delete, data: { confirm: "タスク『#{@task.name}』を削除します。よろしいですか？"}, class: 'btn btn-primary' %>

<table class="table">
  <tbody>
    <tr>
      <th><%= Task.human_attribute_name :id %></th>
      <td><%= @task.id %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name :name %></th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name :description %></th>
      <td><%= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div") %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name :created_at %></th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name :updated_at %></th>
      <td><%= @task.updated_at %></td>
    </tr>
  </tbody>
</table>